[package]
name = "lab4_rust_rust_to_fork"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fork="0.1.22"
libc="0.2.149"